name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.3.20216.6
    - name: Build
      run: dotnet build
    - name: Pack
      if: github.ref == 'refs/heads/master'
      run: dotnet build --configuration Release && dotnet pack --configuration Release --version-suffix "$(date "+%s")" --output .
    - name: Publish (MyGet)
      if: github.ref == 'refs/heads/master'
      run: ls *.nupkg | xargs -i dotnet nuget push {} --api-key ${{ secrets.myget_api }} --source https://www.myget.org/F/tkp1n/api/v3/index.json